CREATE TABLE USUARIO (
    ID INTEGER KEY AUTO_INCREMENT,
    LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    ADMIN BOOL DEFAULT FALSE
);

CREATE TABLE CHARACTER (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    CLAN VARCHAR(255),
    ELEMENTS VARCHAR(255)
);